<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Country\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        foreach ($this->countries() as $country) {
            Country::create($country);
        }
    }

    private function countries() 
    {
      return [
        [
          "name"=> "Afganistán",
          "phone_code"=> "+93",
          "capital"=> "Kabul",
          "flag"=> config('app.url')."/img/flag/afg.svg",
        ],
        [
          "name"=> "Islas Aland",
          "phone_code"=> "+358",
          "capital"=> "Mariehamn",
          "flag"=> config('app.url')."/img/flag/ala.svg",
        ],
        [
          "name"=> "Albania",
          "phone_code"=> "+355",
          "capital"=> "Tirana",
          "flag"=> config('app.url')."/img/flag/alb.svg",
        ],
        [
          "name"=> "Argelia",
          "phone_code"=> "+213",
          "capital"=> "Algiers",
          "flag"=> config('app.url')."/img/flag/dza.svg",
        ],
        [
          "name"=> "Samoa Americana",
          "phone_code"=> "+1684",
          "capital"=> "Pago Pago",
          "flag"=> config('app.url')."/img/flag/asm.svg",
        ],
        [
          "name"=> "Andorra",
          "phone_code"=> "+376",
          "capital"=> "Andorra la Vella",
          "flag"=> config('app.url')."/img/flag/and.svg",
        ],
        [
          "name"=> "Angola",
          "phone_code"=> "+244",
          "capital"=> "Luanda",
          "flag"=> config('app.url')."/img/flag/ago.svg",
        ],
        [
          "name"=> "Anguila",
          "phone_code"=> "+1264",
          "capital"=> "The Valley", 
          "flag"=> config('app.url')."/img/flag/aia.svg",
        ],
        [
          "name"=> "Antártida",
          "phone_code"=> "+672",
          "capital"=> "",
          "flag"=> config('app.url')."/img/flag/ata.svg",
        ],
        [
          "name"=> "Antigua y Barbuda",
          "phone_code"=> "+1268",
          "capital"=> "Saint John's", 
          "flag"=> config('app.url')."/img/flag/atg.svg",
        ],
        [
          "name"=> "Argentina",
          "phone_code"=> "+54",
          "capital"=> "Buenos Aires",
          "flag"=> config('app.url')."/img/flag/arg.svg",
        ],
        [
          "name"=> "Armenia",
          "phone_code"=> "+374",
          "capital"=> "Yerevan", 
          "flag"=> config('app.url')."/img/flag/arm.svg",
        ],
        [
          "name"=> "Aruba",
          "phone_code"=> "+297",
          "capital"=> "Oranjestad", 
          "flag"=> config('app.url')."/img/flag/abw.svg",
        ],
        [
          "name"=> "Australia",
          "phone_code"=> "+61",
          "capital"=> "Canberra",
          "flag"=> config('app.url')."/img/flag/aus.svg",
        ],
        [
          "name"=> "Austria",
          "phone_code"=> "+43",
          "capital"=> "Vienna",
          "flag"=> config('app.url')."/img/flag/aut.svg",
        ],
        [
          "name"=> "Azerbaiyán",
          "phone_code"=> "+994",
          "capital"=> "Baku",
          "flag"=> config('app.url')."/img/flag/aze.svg",
        ],
        [
          "name"=> "Bahamas",
          "phone_code"=> "+1242",
          "capital"=> "Nassau",
          "flag"=> config('app.url')."/img/flag/bhs.svg",
        ],
        [
          "name"=> "Bahréin",
          "phone_code"=> "+973",
          "capital"=> "Manama",
          "flag"=> config('app.url')."/img/flag/bhr.svg",
        ],
        [
          "name"=> "Bangladesh",
          "phone_code"=> "+880",
          "capital"=> "Dhaka",
          "flag"=> config('app.url')."/img/flag/bgd.svg",
        ],
        [
          "name"=> "Barbados",
          "phone_code"=> "+1246",
          "capital"=> "Bridgetown",
          "flag"=> config('app.url')."/img/flag/brb.svg",
        ],
        [
          "name"=> "Belarus",
          "phone_code"=> "+375",
          "capital"=> "Minsk",
          "flag"=> config('app.url')."/img/flag/blr.svg",
        ],
        [
          "name"=> "Bielorrusia",
          "phone_code"=> "+32",
          "capital"=> "Brussels",
          "flag"=> config('app.url')."/img/flag/bel.svg",
        ],
        [
          "name"=> "Belice",
          "phone_code"=> "+501",
          "capital"=> "Belmopan",
          "flag"=> config('app.url')."/img/flag/blz.svg",
        ],
        [
          "name"=> "Benin",
          "phone_code"=> "+229",
          "capital"=> "Porto-Novo",
          "flag"=> config('app.url')."/img/flag/ben.svg",
        ],
        [
          "name"=> "Islas Bermudas",
          "phone_code"=> "+1441",
          "capital"=> "Hamilton",
          "flag"=> config('app.url')."/img/flag/bmu.svg",
        ],
        [
          "name"=> "Bután",
          "phone_code"=> "+975",
          "capital"=> "Thimphu",
          "flag"=> config('app.url')."/img/flag/btn.svg",
        ],
        [
          "name"=> "Bolivia (Estado Plurinacional de)",
          "phone_code"=> "+591",
          "capital"=> "Sucre",
          "flag"=> config('app.url')."/img/flag/bol.svg",
        ],
        [
          "name" => "Bonaire, Sint Eustatius y Saba",
          "phone_code"=> "+5997",
          "capital"=> "Kralendijk",
          "flag"=> config('app.url')."/img/flag/bes.svg",
        ],
        [
          "name"=> "Bosnia y Herzegovina",
          "phone_code"=> "+387",
          "capital"=> "Sarajevo",
          "flag"=> config('app.url')."/img/flag/bih.svg",
        ],
        [
          "name"=> "Botswana",
          "phone_code"=> "+267",
          "capital"=> "Gaborone",
          "flag"=> config('app.url')."/img/flag/bwa.svg",
        ],
        [
          "name"=> "Isla Bouvet",
          "phone_code"=> "",
          "capital"=> "",
          "flag"=> config('app.url')."/img/flag/bvt.svg",
        ],
        [
          "name"=> "Brasil",
          "phone_code"=> "+55",
          "capital"=> "Brasília",
          "flag"=> config('app.url')."/img/flag/bra.svg",
        ],
        [
          "name"=> "Territorio Británico del Océano Índico",
          "phone_code"=> "+246",
          "capital"=> "Diego Garcia",
          "flag"=> config('app.url')."/img/flag/iot.svg",
        ],
        [
          "name"=> "Islas menores alejadas de los Estados Unidos",
          "phone_code"=> "",
          "capital"=> "", 
          "flag"=> config('app.url')."/img/flag/umi.svg",
        ],
        [
          "name"=> "Islas Vírgenes (Británicas)",
          "phone_code"=> "+1284",
          "capital"=> "Road Town",
          "flag"=> config('app.url')."/img/flag/vgb.svg",
        ],
        [
          "name"=> "Islas Vírgenes (EE. UU.)",
          "phone_code"=> "+1 340",
          "capital"=> "Charlotte Amalie",
          "flag"=> config('app.url')."/img/flag/vir.svg",
        ],
        [
          "name"=> "Brunei Darussalam",
          "phone_code"=> "+673",
          "capital"=> "Bandar Seri Begawan",
          "flag"=> config('app.url')."/img/flag/brn.svg",
        ],
        [
          "name"=> "Bulgaria",
          "phone_code"=> "+359",
          "capital"=> "Sofia",
          "flag"=> config('app.url')."/img/flag/bgr.svg",
        ],
        [
          "name"=> "Burkina Faso",
          "phone_code"=> "+226",
          "capital"=> "Ouagadougou",
          "flag"=> config('app.url')."/img/flag/bfa.svg",
        ],
        [
          "name"=> "Burundi",
          "phone_code"=> "+257",
          "capital"=> "Bujumbura",
          "flag"=> config('app.url')."/img/flag/bdi.svg",
        ],
        [
          "name"=> "Camboya",
          "phone_code"=> "+855",
          "capital"=> "Phnom Penh",
          "flag"=> config('app.url')."/img/flag/khm.svg",
        ],
        [
          "name"=> "Camerún",
          "phone_code"=> "+237",
          "capital"=> "Yaoundé",
          "flag"=> config('app.url')."/img/flag/cmr.svg",
        ],
        [
          "name"=> "Canadá",
          "phone_code"=> "+1",
          "capital"=> "Ottawa",
          "flag"=> config('app.url')."/img/flag/can.svg",
        ],
        [
          "name"=> "Cabo Verde",
          "phone_code"=> "+238",
          "capital"=> "Praia",
          "flag"=> config('app.url')."/img/flag/cpv.svg",
        ],
        [
          "name"=> "Islas Caimán",
          "phone_code"=> "+1345",
          "capital"=> "George Town",
          "flag"=> config('app.url')."/img/flag/cym.svg",
        ],
        [
          "name"=> "República Centroafricana",
          "phone_code"=> "+236",
          "capital"=> "Bangui",
          "flag"=> config('app.url')."/img/flag/caf.svg",
        ],
        [
          "name"=> "Chad",
          "phone_code"=> "+235",
          "capital"=> "N'Djamena",
          "flag"=> config('app.url')."/img/flag/tcd.svg",
        ],
        [
          "name"=> "Chile",
          "phone_code"=> "+56",
          "capital"=> "Santiago",
          "flag"=> config('app.url')."/img/flag/chl.svg",
        ],
        [
          "name"=> "China",
          "phone_code"=> "+86",
          "capital"=> "Beijing",
          "flag"=> config('app.url')."/img/flag/chn.svg",
        ],
        [
          "name"=> "Isla de Navidad",
          "phone_code"=> "+61",
          "capital"=> "Flying Fish Cove",
          "flag"=> config('app.url')."/img/flag/cxr.svg",
        ],
        [
          "name"=> "Islas Cocos (Keeling)",
          "phone_code"=> "+61",
          "capital"=> "West Island",
          "flag"=> config('app.url')."/img/flag/cck.svg",
        ],
        [
          "name"=> "Colombia",
          "phone_code"=> "+57",
          "capital"=> "Bogotá",
          "flag"=> config('app.url')."/img/flag/col.svg",
        ],
        [
          "name"=> "Comoras",
          "phone_code"=> "+269",
          "capital"=> "Moroni",
          "flag"=> config('app.url')."/img/flag/com.svg",
        ],
        [
          "name"=> "Congo",
          "phone_code"=> "+242",
          "capital"=> "Brazzaville",
          "flag"=> config('app.url')."/img/flag/cog.svg",
        ],
        [
          "name"=> "Congo (República Democrática del)",
          "phone_code"=> "+243",
          "capital"=> "Kinshasa",
          "flag"=> config('app.url')."/img/flag/cod.svg",
        ],
        [
          "name"=> "Islas Cook",
          "phone_code"=> "+682",
          "capital"=> "Avarua",
          "flag"=> config('app.url')."/img/flag/cok.svg",
        ],
        [
          "name"=> "Costa Rica",
          "phone_code"=> "+506",
          "capital"=> "San José",
          "flag"=> config('app.url')."/img/flag/cri.svg",
        ],
        [
          "name"=> "Croacia",
          "phone_code"=> "+385",
          "capital"=> "Zagreb",
          "flag"=> config('app.url')."/img/flag/hrv.svg",
        ],
        [
          "name"=> "Cuba",
          "phone_code"=> "+53",
          "capital"=> "Havana",
          "flag"=> config('app.url')."/img/flag/cub.svg",
        ],
        [
          "name"=> "Curazao",
          "phone_code"=> "+599",
          "capital"=> "Willemstad",
          "flag"=> config('app.url')."/img/flag/cuw.svg",
        ],
        [
          "name"=> "Chipre",
          "phone_code"=> "+357",
          "capital"=> "Nicosia",
          "flag"=> config('app.url')."/img/flag/cyp.svg",
        ],
        [
          "name"=> "Republica checa",
          "phone_code"=> "+420",
          "capital"=> "Prague",
          "flag"=> config('app.url')."/img/flag/cze.svg",
        ],
        [
          "name"=> "Dinamarca",
          "phone_code"=> "+45",
          "capital"=> "Copenhagen",
          "flag"=> config('app.url')."/img/flag/dnk.svg",
        ],
        [
          "name"=> "Djibouti",
          "phone_code"=> "+253",
          "capital"=> "Djibouti",
          "flag"=> config('app.url')."/img/flag/dji.svg",
        ],
        [
          "name"=> "Dominica",
          "phone_code"=> "+1767",
          "capital"=> "Roseau",
          "flag"=> config('app.url')."/img/flag/dma.svg",
        ],
        [
          "name"=> "República Dominicana",
          "phone_code"=> "+1849",
          "capital"=> "Santo Domingo",
          "flag"=> config('app.url')."/img/flag/dom.svg",
        ],
        [
          "name"=> "Ecuador",
          "phone_code"=> "+593",
          "capital"=> "Quito",
          "flag"=> config('app.url')."/img/flag/ecu.svg",
        ],
        [
          "name"=> "Egipto",
          "phone_code"=> "+20",
          "capital"=> "Cairo",
          "flag"=> config('app.url')."/img/flag/egy.svg",
        ],
        [
          "name"=> "El Salvador",
          "phone_code"=> "+503",
          "capital"=> "San Salvador",
          "flag"=> config('app.url')."/img/flag/slv.svg",
        ],
        [
          "name"=> "Guinea Ecuatorial",
          "phone_code"=> "+240",
          "capital"=> "Malabo",
          "flag"=> config('app.url')."/img/flag/gnq.svg",
        ],
        [
          "name"=> "Eritrea",
          "phone_code"=> "+291",
          "capital"=> "Asmara",
          "flag"=> config('app.url')."/img/flag/eri.svg",
        ],
        [
          "name"=> "Estonia",
          "phone_code"=> "+372",
          "capital"=> "Tallinn",
          "flag"=> config('app.url')."/img/flag/est.svg",
        ],
        [
          "name"=> "Etiopía",
          "phone_code"=> "+251",
          "capital"=> "Addis Ababa",
          "flag"=> config('app.url')."/img/flag/eth.svg",
        ],
        [
          "name"=> "Islas Falkland (Malvinas)",
          "phone_code"=> "+500",
          "capital"=> "Stanley",
          "flag"=> config('app.url')."/img/flag/flk.svg",
        ],
        [
          "name"=> "Islas Faroe",
          "phone_code"=> "+298",
          "capital"=> "Tórshavn",
          "flag"=> config('app.url')."/img/flag/fro.svg",
        ],
        [
          "name"=> "Fiyi",
          "phone_code"=> "+679",
          "capital"=> "Suva",
          "flag"=> config('app.url')."/img/flag/fji.svg",
        ],
        [
          "name"=> "Finlandia",
          "phone_code"=> "+358",
          "capital"=> "Helsinki",
          "flag"=> config('app.url')."/img/flag/fin.svg",
        
        ],
        [
          "name"=> "Francia",
          "phone_code"=> "+33",
          "capital"=> "Paris",
          "flag"=> config('app.url')."/img/flag/fra.svg",
        ],
        [
          "name"=> "Guayana Francesa",
          "phone_code"=> "+594",
          "capital"=> "Cayenne",
          "flag"=> config('app.url')."/img/flag/guf.svg",
        ],
        [
          "name"=> "Polinesia francés",
          "phone_code"=> "+689",
          "capital"=> "Papeetē",
          "flag"=> config('app.url')."/img/flag/pyf.svg",
        ],
        [
          "name"=> "Territorios Franceses del Sur",
          "phone_code"=> "",
          "capital"=> "Port-aux-Français",
          "flag"=> config('app.url')."/img/flag/atf.svg",
        ],
        [
          "name"=> "Gabón",
          "phone_code"=> "+241",
          "capital"=> "Libreville",
          "flag"=> config('app.url')."/img/flag/gab.svg",
        ],
        [
          "name"=> "Gambia",
          "phone_code"=> "+220",
          "capital"=> "Banjul",
          "flag"=> config('app.url')."/img/flag/gmb.svg",
        ],
        [
          "name"=> "Georgia",
          "phone_code"=> "+995",
          "capital"=> "Tbilisi",
          "flag"=> config('app.url')."/img/flag/geo.svg",
        ],
        [
          "name"=> "Alemania",
          "phone_code"=> "+49",
          "capital"=> "Berlin",
          "flag"=> config('app.url')."/img/flag/deu.svg",
        ],
        [
          "name"=> "Ghana",
          "phone_code"=> "+233",
          "capital"=> "Accra",
          "flag"=> config('app.url')."/img/flag/gha.svg",
        ],
        [
          "name"=> "Gibraltar",
          "phone_code"=> "+350",
          "capital"=> "Gibraltar",
          "flag"=> config('app.url')."/img/flag/gib.svg",
        ],
        [
          "name"=> "Grecia",
          "phone_code"=> "+30",
          "capital"=> "Athens",
          "flag"=> config('app.url')."/img/flag/grc.svg",
        ],
        [
          "name"=> "Groenlandia",
          "phone_code"=> "+299",
          "capital"=> "Nuuk",
          "flag"=> config('app.url')."/img/flag/grl.svg",
        ],
        [
          "name"=> "Granada",
          "phone_code"=> "+1473",
          "capital"=> "St. George's",
          "flag"=> config('app.url')."/img/flag/grd.svg",
        ],
        [
          "name" => "Guadalupe",
          "phone_code" => "590",
          "capital"=> "Basse-Terre",
          "flag"=> config('app.url')."/img/flag/glp.svg",
        ],
        [
          "name"=> "Guam",
          "phone_code"=> "+1671",
          "capital"=> "Hagåtña",
          "flag"=> config('app.url')."/img/flag/gum.svg",
        ],
        [
          "name"=> "Guatemala",
          "phone_code"=> "+502",
          "capital"=> "Guatemala City",
          "flag"=> config('app.url')."/img/flag/gtm.svg",
        ],
        [
          "name"=> "Guernsey",
          "phone_code"=> "+44",
          "capital"=> "St. Peter Port",
          "flag"=> config('app.url')."/img/flag/ggy.svg",
        ],
        [
          "name"=> "Guinea",
          "phone_code"=> "+224",
          "capital"=> "Conakry",
          "flag"=> config('app.url')."/img/flag/gin.svg",
        ],
        [
          "name"=> "Guinea-Bissau",
          "phone_code"=> "+245",
          "capital"=> "Bissau",
          "flag"=> config('app.url')."/img/flag/gnb.svg",
        ],
        [
          "name"=> "Guayana",
          "phone_code"=> "+592",
          "capital"=> "Georgetown",
          "flag"=> config('app.url')."/img/flag/guy.svg",
        ],
        [
          "name"=> "Haití",
          "phone_code"=> "+509",
          "capital"=> "Port-au-Prince",
          "flag"=> config('app.url')."/img/flag/hti.svg",
        ],
        [
          "name"=> "Islas Heard y McDonald",
          "phone_code"=> "",
          "capital"=> "",
          "flag"=> config('app.url')."/img/flag/hmd.svg",
        ],
        [
          "name"=> "Santa Sede",
          "phone_code"=> "+379",
          "capital"=> "Rome",
          "flag"=> config('app.url')."/img/flag/vat.svg",
        ],
        [
          "name"=> "Honduras",
          "phone_code"=> "+504",
          "capital"=> "Tegucigalpa",
          "flag"=> config('app.url')."/img/flag/hnd.svg",
        ],
        [
          "name"=> "Hong Kong",
          "phone_code"=> "+852",
          "capital"=> "City of Victoria",
          "flag"=> config('app.url')."/img/flag/hkg.svg",
        ],
        [
          "name"=> "Hungría",
          "phone_code"=> "+36",
          "capital"=> "Budapest",
          "flag"=> config('app.url')."/img/flag/hun.svg",
        ],
        [
          "name"=> "Islandia",
          "phone_code"=> "+354",
          "capital"=> "Reykjavík",
          "flag"=> config('app.url')."/img/flag/isl.svg",
        ],
        [
          "name"=> "India",
          "phone_code"=> "+91",
          "capital"=> "New Delhi",
          "flag"=> config('app.url')."/img/flag/ind.svg",
        ],
        [
          "name"=> "Indonesia",
          "phone_code"=> "+62",
          "capital"=> "Jakarta",
          "flag"=> config('app.url')."/img/flag/idn.svg",
        ],
        [
          "name"=> "Costa de Marfil",
          "phone_code"=> "+225",
          "capital"=> "Yamoussoukro",
          "flag"=> config('app.url')."/img/flag/civ.svg",
        ],
        [
          "name"=> "Irán (República Islámica de)",
          "phone_code"=> "+98",
          "capital"=> "Tehran",
          "flag"=> config('app.url')."/img/flag/irn.svg",
        ],
        [
          "name"=> "Irak",
          "phone_code"=> "+964",
          "capital"=> "Baghdad",
          "flag"=> config('app.url')."/img/flag/irq.svg",
        ],
        [
          "name"=> "Irlanda",
          "phone_code"=> "+353",
          "capital"=> "Dublin",
          "flag"=> config('app.url')."/img/flag/irl.svg",
        ],
        [
          "name"=> "Isla del hombre",
          "phone_code"=> "+44",
          "capital"=> "Douglas",
          "flag"=> config('app.url')."/img/flag/imn.svg",
        ],
        [
          "name"=> "Israel",
          "phone_code"=> "+972",
          "capital"=> "Jerusalem",
          "flag"=> config('app.url')."/img/flag/isr.svg",
        ],
        [
          "name"=> "Italia",
          "phone_code"=> "+39",
          "capital"=> "Rome",
          "flag"=> config('app.url')."/img/flag/ita.svg",
          ],
        [
          "name"=> "Jamaica",
          "phone_code"=> "+1876",
          "capital"=> "Kingston",
          "flag"=> config('app.url')."/img/flag/jam.svg",
        ],
        [
          "name"=> "Japón",
          "phone_code"=> "+81",
          "capital"=> "Tokyo",
          "flag"=> config('app.url')."/img/flag/jpn.svg",
        ],
        [
          "name"=> "Jersey",
          "phone_code"=> "+44",
          "capital"=> "Saint Helier",
          "flag"=> config('app.url')."/img/flag/jey.svg",
        ],
        [
          "name"=> "Jordán",
          "phone_code"=> "+962",
          "capital"=> "Amman",
          "flag"=> config('app.url')."/img/flag/jor.svg",
        ],
        [
          "name"=> "Kazajstán",
          "phone_code"=> "+7",
          "capital"=> "Astana",
          "flag"=> config('app.url')."/img/flag/kaz.svg",
        ],
        [
          "name"=> "Kenia",
          "phone_code"=> "+254",
          "capital"=> "Nairobi",
          "flag"=> config('app.url')."/img/flag/ken.svg",
        ],
        [
          "name"=> "Kiribati",
          "phone_code"=> "+686",
          "capital"=> "South Tarawa",
          "flag"=> config('app.url')."/img/flag/kir.svg",
        ],
        [
          "name"=> "Kuwait",
          "phone_code"=> "+965",
          "capital"=> "Kuwait City",
          "flag"=> config('app.url')."/img/flag/kwt.svg",
        ],
        [
          "name"=> "Kirguistán",
          "phone_code"=> "+996",
          "capital"=> "Bishkek",
          "flag"=> config('app.url')."/img/flag/kgz.svg",
        ],
        [
          "name"=> "República Democrática Popular Lao",
          "phone_code"=> "+856",
          "capital"=> "Vientiane",
          "flag"=> config('app.url')."/img/flag/lao.svg",
        ],
        [
          "name"=> "Letonia",
          "phone_code"=> "+371",
          "capital"=> "Riga",
          "flag"=> config('app.url')."/img/flag/lva.svg",
        ],
        [
          "name"=> "Líbano",
          "phone_code"=> "+961",
          "capital"=> "Beirut",
          "flag"=> config('app.url')."/img/flag/lbn.svg",
        ],
        [
          "name"=> "Lesoto",
          "phone_code"=> "+266",
          "capital"=> "Maseru",
          "flag"=> config('app.url')."/img/flag/lso.svg",
        ],
        [
          "name"=> "Liberia",
          "phone_code"=> "+231",
          "capital"=> "Monrovia",
          "flag"=> config('app.url')."/img/flag/lbr.svg",
        ],
        [
          "name"=> "Libia",
          "phone_code"=> "+218",
          "capital"=> "Tripoli",
          "flag"=> config('app.url')."/img/flag/lby.svg",
        ],
        [
          "name"=> "Liechtenstein",
          "phone_code"=> "+423",
          "capital"=> "Vaduz",
          "flag"=> config('app.url')."/img/flag/lie.svg",
        ],
        [
          "name"=> "Lituania",
          "phone_code"=> "+370",
          "capital"=> "Vilnius",
          "flag"=> config('app.url')."/img/flag/ltu.svg",
        ],
        [
          "name"=> "Luxemburgo",
          "phone_code"=> "+352",
          "capital"=> "Luxembourg",
          "flag"=> config('app.url')."/img/flag/lux.svg",
        ],
        [
          "name"=> "Macao",
          "phone_code"=> "+853",
          "capital"=> "",
          "flag"=> config('app.url')."/img/flag/mac.svg",
        ],
        [
          "name"=> "Macedonia (ex República Yugoslava de)",
          "phone_code"=> "+389",
          "capital"=> "Skopje",
          "flag"=> config('app.url')."/img/flag/mkd.svg",
        ],
        [
          "name"=> "Madagascar",
          "phone_code"=> "+261",
          "capital"=> "Antananarivo",
          "flag"=> config('app.url')."/img/flag/mdg.svg",
        ],
        [
          "name"=> "Malawi",
          "phone_code"=> "+265",
          "capital"=> "Lilongwe",
          "flag"=> config('app.url')."/img/flag/mwi.svg",
        ],
        [
          "name"=> "Malasia",
          "phone_code"=> "+60",
          "capital"=> "Kuala Lumpur",
          "flag"=> config('app.url')."/img/flag/mys.svg",
        ],
        [
          "name"=> "Maldivas",
          "phone_code"=> "+960",
          "capital"=> "Malé",
          "flag"=> config('app.url')."/img/flag/mdv.svg",
        ],
        [
          "name"=> "Mali",
          "phone_code"=> "+223",
          "capital"=> "Bamako",
          "flag"=> config('app.url')."/img/flag/mli.svg",
        ],
        [
          "name"=> "Malta",
          "phone_code"=> "+356",
          "capital"=> "Valletta",
          "flag"=> config('app.url')."/img/flag/mlt.svg",
        ],
        [
          "name"=> "Islas Marshall",
          "phone_code"=> "+692",
          "capital"=> "Majuro",
          "flag"=> config('app.url')."/img/flag/mhl.svg",
        ],
        [
          "name"=> "Martinica",
          "phone_code"=> "+596",
          "capital"=> "Fort-de-France",
          "flag"=> config('app.url')."/img/flag/mtq.svg",
        ],
        [
          "name"=> "Mauritania",
          "phone_code"=> "+222",
          "capital"=> "Nouakchott",
          "flag"=> config('app.url')."/img/flag/mrt.svg",
        ],
        [
          "name"=> "Mauricio",
          "phone_code"=> "+230",
          "capital"=> "Port Louis",
          "flag"=> config('app.url')."/img/flag/mus.svg",
        ],
        [
          "name"=> "Mayotte",
          "phone_code"=> "+262",
          "capital"=> "Mamoudzou",
          "flag"=> config('app.url')."/img/flag/myt.svg",
        ],
        [
          "name"=> "México",
          "phone_code"=> "+52",
          "capital"=> "Mexico City",
          "flag"=> config('app.url')."/img/flag/mex.svg",
        ],
        [
          "name"=> "Micronesia (Estados Federados de)",
          "phone_code"=> "+691",
          "capital"=> "Palikir",
          "flag"=> config('app.url')."/img/flag/fsm.svg",
        ],
        [
          "name"=> "Moldavia, República de)",
          "phone_code"=> "+373",
          "capital"=> "Chișinău",
          "flag"=> config('app.url')."/img/flag/mda.svg",
        ],
        [
          "name"=> "Mónaco",
          "phone_code"=> "+377",
          "capital"=> "Monaco",
          "flag"=> config('app.url')."/img/flag/mco.svg",
        ],
        [
          "name"=> "Mongolia",
          "phone_code"=> "+976",
          "capital"=> "Ulan Bator",
          "flag"=> config('app.url')."/img/flag/mng.svg",
        ],
        [
          "name"=> "Montenegro",
          "phone_code"=> "+382",
          "capital"=> "Podgorica",
          "flag"=> config('app.url')."/img/flag/mne.svg",
        ],
        [
          "name"=> "Montserrat",
          "phone_code"=> "+1664",
          "capital"=> "Plymouth",
          "flag"=> config('app.url')."/img/flag/msr.svg",
        ],
        [
          "name"=> "Marruecos",
          "phone_code"=> "+212",
          "capital"=> "Rabat",
          "flag"=> config('app.url')."/img/flag/mar.svg",
        ],
        [
          "name"=> "Mozambique",
          "phone_code"=> "+258",
          "capital"=> "Maputo",
          "flag"=> config('app.url')."/img/flag/moz.svg",
        ],
        [
          "name"=> "Myanmar",
          "phone_code"=> "+95",
          "capital"=> "Naypyidaw",
          "flag"=> config('app.url')."/img/flag/mmr.svg",
        ],
        [
          "name"=> "Namibia",
          "phone_code"=> "+264",
          "capital"=> "Windhoek",
          "flag"=> config('app.url')."/img/flag/nam.svg",
        ],
        [
          "name"=> "Nauru",
          "phone_code"=> "+674",
          "capital"=> "Yaren",
          "flag"=> config('app.url')."/img/flag/nru.svg",
        ],
        [
          "name"=> "Nepal",
          "phone_code"=> "+977",
          "capital"=> "Kathmandu",
          "flag"=> config('app.url')."/img/flag/npl.svg",
        ],
        [
          "name"=> "Países Bajos",
          "phone_code"=> "+31",
          "capital"=> "Amsterdam",
          "flag"=> config('app.url')."/img/flag/nld.svg",
        ],
        [
          "name"=> "Nueva Caledonia",
          "phone_code"=> "+687",
          "capital"=> "Nouméa",
          "flag"=> config('app.url')."/img/flag/ncl.svg",
        ],
        [
          "name"=> "Nueva Zelanda",
          "phone_code"=> "+64",
          "capital"=> "Wellington",
          "flag"=> config('app.url')."/img/flag/nzl.svg",
        ],
        [
          "name"=> "Nicaragua",
          "phone_code"=> "+505",
          "capital"=> "Managua",
          "flag"=> config('app.url')."/img/flag/nic.svg",
        ],
        [
          "name"=> "Níger",
          "phone_code"=> "+227",
          "capital"=> "Niamey",
          "flag"=> config('app.url')."/img/flag/ner.svg",
        ],
        [
          "name"=> "Nigeria",
          "phone_code"=> "+234",
          "capital"=> "Abuja",
          "flag"=> config('app.url')."/img/flag/nga.svg",
        ],
        [
          "name"=> "Niue",
          "phone_code"=> "+683",
          "capital"=> "Alofi",
          "flag"=> config('app.url')."/img/flag/niu.svg",
        ],
        [
          "name"=> "Isla Norfolk",
          "phone_code"=> "+672",
          "capital"=> "Kingston",
          "flag"=> config('app.url')."/img/flag/nfk.svg",
        ],
        [
          "name"=> "República de Corea, Popular Democrática de)",
          "phone_code"=> "+850",
          "capital"=> "Pyongyang",
          "flag"=> config('app.url')."/img/flag/prk.svg",
        ],
        [
          "name"=> "Islas Marianas del Norte",
          "phone_code"=> "+1670",
          "capital"=> "Saipan",
          "flag"=> config('app.url')."/img/flag/mnp.svg",
        ],
        [
          "name"=> "Noruega",
          "phone_code"=> "+47",
          "capital"=> "Oslo",
          "flag"=> config('app.url')."/img/flag/nor.svg",
        ],
        [
          "name"=> "Omán",
          "phone_code"=> "+968",
          "capital"=> "Muscat",
          "flag"=> config('app.url')."/img/flag/omn.svg",
        ],
        [
          "name"=> "Pakistán",
          "phone_code"=> "+92",
          "capital"=> "Islamabad",
          "flag"=> config('app.url')."/img/flag/pak.svg",
        ],
        [
          "name"=> "Palau",
          "phone_code"=> "+680",
          "capital"=> "Ngerulmud",
          "flag"=> config('app.url')."/img/flag/plw.svg",
        ],
        [
          "name"=> "Estado de Palestina",
          "phone_code"=> "+970",
          "capital"=> "Ramallah",
          "flag"=> config('app.url')."/img/flag/pse.svg",
        ],
        [
          "name"=> "Panamá",
          "phone_code"=> "+507",
          "capital"=> "Panama City",
          "flag"=> config('app.url')."/img/flag/pan.svg",
        ],
        [
          "name"=> "Papúa Nueva Guinea",
          "phone_code"=> "+675",
          "capital"=> "Port Moresby",
          "flag"=> config('app.url')."/img/flag/png.svg",
        ],
        [
          "name"=> "Paraguay",
          "phone_code"=> "+595",
          "capital"=> "Asunción",
          "flag"=> config('app.url')."/img/flag/pry.svg",
        ],
        [
          "name"=> "Perú",
          "phone_code"=> "+51",
          "capital"=> "Lima",
          "flag"=> config('app.url')."/img/flag/per.svg",
        ],
        [
          "name"=> "Filipinas",
          "phone_code"=> "+63",
          "capital"=> "Manila",
          "flag"=> config('app.url')."/img/flag/phl.svg",
        ],
        [
          "name"=> "Pitcairn",
          "phone_code"=> "+64",
          "capital"=> "Adamstown",
          "flag"=> config('app.url')."/img/flag/pcn.svg",
        ],
          [
          "name"=> "Polonia",
          "phone_code"=> "+48",
          "capital"=> "Warsaw",
          "flag"=> config('app.url')."/img/flag/pol.svg",
        ],
        [
          "name"=> "Portugal",
          "phone_code"=> "+351",
          "capital"=> "Lisbon",
          "flag"=> config('app.url')."/img/flag/pri.svg",
        ],
        [
          "name"=> "Katar",
          "phone_code"=> "+974",
          "capital"=> "Doha",
          "flag"=> config('app.url')."/img/flag/qat.svg",
        ],
        [
          "name"=> "República de Kosovo",
          "phone_code"=> "+383",
          "capital"=> "Pristina",
          "flag"=> config('app.url')."/img/flag/kos.svg",
        ],
        [
          "name"=> "Reunión",
          "phone_code"=> "+262",
          "capital"=> "Saint-Denis",
          "flag"=> config('app.url')."/img/flag/reu.svg",
        ],
        [
          "name"=> "Rumania",
          "phone_code"=> "+40",
          "capital"=> "Bucharest",
          "flag"=> config('app.url')."/img/flag/rou.svg",
        ],
        [
          "name"=> "Federación Rusa",
          "phone_code"=> "+7",
          "capital"=> "Moscow",
          "flag"=> config('app.url')."/img/flag/rus.svg",
        ],
        [
          "name"=> "Ruanda",
          "phone_code"=> "+250",
          "capital"=> "Kigali",
          "flag"=> config('app.url')."/img/flag/rwa.svg",
        ],
        // [
        
        // ],
        [
          "name"=> "Santa Elena, Ascensión y Tristán da Cunha",
          "phone_code"=> "+290",
          "capital"=> "Jamestown",
          "flag"=> config('app.url')."/img/flag/shn.svg",
        ],
        [
          "name"=> "Saint Kitts y Nevis",
          "phone_code"=> "+1869",
          "capital"=> "Basseterre",
          "flag"=> config('app.url')."/img/flag/kna.svg",
        ],
        [
          "name"=> "Santa Lucía",
          "phone_code"=> "+1758",
          "capital"=> "Castries",
          "flag"=> config('app.url')."/img/flag/lca.svg",
        ],
        [
          "name"=> "San Martín (parte francesa)",
          "phone_code"=> "+590",
          "capital"=> "Marigot",
          "flag"=> config('app.url')."/img/flag/maf.svg",
        ],
        [
          "name"=> "San Pedro y Miquelón",
          "phone_code"=> "+508",
          "capital"=> "Saint-Pierre",
          "flag"=> config('app.url')."/img/flag/spm.svg",
        ],
        [
          "name"=> "San Vicente y las Granadinas",
          "phone_code"=> "+1784",
          "capital"=> "Kingstown",
          "flag"=> config('app.url')."/img/flag/vct.svg",
        ],
        [
          "name"=> "Samoa",
          "phone_code"=> "+685",
          "capital"=> "Apia",
          "flag"=> config('app.url')."/img/flag/wsm.svg",
        ],
        [
          "name"=> "San Marino",
          "phone_code"=> "+378",
          "capital"=> "City of San Marino",
          "flag"=> config('app.url')."/img/flag/smr.svg",
        ],
        [
          "name"=> "Santo Tomé y Príncipe",
          "phone_code"=> "+239",
          "capital"=> "São Tomé",
          "flag"=> config('app.url')."/img/flag/stp.svg",
        ],
        [
          "name"=> "Arabia Saudita",
          "phone_code"=> "+966",
          "capital"=> "Riyadh",
          "flag"=> config('app.url')."/img/flag/sau.svg",
        ],
        [
          "name"=> "Senegal",
          "phone_code"=> "+221",
          "capital"=> "Dakar",
          "flag"=> config('app.url')."/img/flag/sen.svg",
        ],
        [
          "name"=> "Serbia",
          "phone_code"=> "+381",
          "capital"=> "Belgrade",
          "flag"=> config('app.url')."/img/flag/srb.svg",
        ],
        [
          "name"=> "Seychelles",
          "phone_code"=> "+248",
          "capital"=> "Victoria",
          "flag"=> config('app.url')."/img/flag/syc.svg",
        ],
        [
          "name"=> "Sierra Leona",
          "phone_code"=> "+232",
          "capital"=> "Freetown",
          "flag"=> config('app.url')."/img/flag/sle.svg",
          ],
        [
          "name"=> "Singapur",
          "phone_code"=> "+65",
          "capital"=> "Singapore",
          "flag"=> config('app.url')."/img/flag/sgp.svg",
        ],
        [
          "name"=> "Sint Maarten (parte holandesa)",
          "phone_code"=> "+1721",
          "capital"=> "Philipsburg",
          "flag"=> config('app.url')."/img/flag/sxm.svg",
        ],
        [
          "name"=> "Eslovaquia",
          "phone_code"=> "+421",
          "capital"=> "Bratislava",
          "flag"=> config('app.url')."/img/flag/svk.svg",
        ],
        [
          "name"=> "Eslovenia",
          "phone_code"=> "+386",
          "capital"=> "Ljubljana",
          "flag"=> config('app.url')."/img/flag/svn.svg",
        ],
        [
          "name"=> "Islas Salomón",
          "phone_code"=> "+677",
          "capital"=> "Honiara",
          "flag"=> config('app.url')."/img/flag/slb.svg",
        ],
        [
          "name"=> "Somalia",
          "phone_code"=> "+252",
          "capital"=> "Mogadishu",
          "flag"=> config('app.url')."/img/flag/som.svg",
        ],
        [
          "name"=> "Sudáfrica",
          "phone_code"=> "+27",
          "capital"=> "Pretoria",
          "flag"=> config('app.url')."/img/flag/zaf.svg",
        ],
        [
          "name"=> "Georgia del sur y las islas Sandwich del sur",
          "phone_code"=> "+500",
          "capital"=> "King Edward Point",
          "flag"=> config('app.url')."/img/flag/sgs.svg",
        ],
        [
          "name"=> "República de Corea",
          "phone_code"=> "+82",
          "capital"=> "Seoul",
          "flag"=> config('app.url')."/img/flag/kor.svg",
        ],
        [
          "name"=> "Sudán del Sur",
          "phone_code"=> "+211",
          "capital"=> "Juba",
          "flag"=> config('app.url')."/img/flag/ssd.svg",
        ],
        [
          "name"=> "España",
          "phone_code"=> "+34",
          "capital"=> "Madrid",
          "flag"=> config('app.url')."/img/flag/esp.svg",
        ],
        [
          "name"=> "Sri Lanka",
          "phone_code"=> "+94",
          "capital"=> "Colombo",
          "flag"=> config('app.url')."/img/flag/lka.svg",
        ],
        [
          "name"=> "Sudán",
          "phone_code"=> "+249",
          "capital"=> "Khartoum",
          "flag"=> config('app.url')."/img/flag/sdn.svg",
        ],
        [
          "name"=> "Surinam",
          "phone_code"=> "+597",
          "capital"=> "Paramaribo",
          "flag"=> config('app.url')."/img/flag/sur.svg",
        ],
        [
          "name"=> "Svalbard y Jan Mayen",
          "phone_code"=> "+4779",
          "capital"=> "Longyearbyen",
          "flag"=> config('app.url')."/img/flag/sjm.svg",
        ],
        [
          "name"=> "Swazilandia",
          "phone_code"=> "+268",
          "capital"=> "Lobamba",
          "flag"=> config('app.url')."/img/flag/swz.svg",
        ],
        [
          "name"=> "Suecia",
          "phone_code"=> "+46",
          "capital"=> "Stockholm",
          "flag"=> config('app.url')."/img/flag/swe.svg",
        ],
        [
          "name"=> "Suiza",
          "phone_code"=> "+41",
          "capital"=> "Bern",
          "flag"=> config('app.url')."/img/flag/che.svg",
        ],
        [
          "name"=> "República Árabe Siria",
          "phone_code"=> "+963",
          "capital"=> "Damascus",
          "flag"=> config('app.url')."/img/flag/syr.svg",
        ],
        [
          "name"=> "Taiwán",
          "phone_code"=> "+886",
          "capital"=> "Taipei",
          "flag"=> config('app.url')."/img/flag/twn.svg",
        ],
        [
          "name"=> "Tayikistán",
          "phone_code"=> "+992",
          "capital"=> "Dushanbe",
          "flag"=> config('app.url')."/img/flag/tjk.svg",
        ],
        [
          "name"=> "República Unida de Tanzania",
          "phone_code"=> "+255",
          "capital"=> "Dodoma",
          "flag"=> config('app.url')."/img/flag/tza.svg",
        ],
        [
          "name"=> "Tailandia",
          "phone_code"=> "+66",
          "capital"=> "Bangkok",
          "flag"=> config('app.url')."/img/flag/tha.svg",
        ],
        [
          "name"=> "Timor-Leste",
          "phone_code"=> "+670",
          "capital"=> "Dili",
          "flag"=> config('app.url')."/img/flag/tls.svg",
        ],
        [
          "name"=> "Togo (África Occidental)",
          "phone_code"=> "+228",
          "capital"=> "Lomé",
          "flag"=> config('app.url')."/img/flag/tgo.svg",
        ],
        [
          "name"=> "Tokelau",
          "phone_code"=> "+690",
          "capital"=> "Fakaofo",
          "flag"=> config('app.url')."/img/flag/tkl.svg",
        ],
        [
          "name"=> "Tonga",
          "phone_code"=> "+676",
          "capital"=> "Nuku'alofa",
          "flag"=> config('app.url')."/img/flag/ton.svg",
        ],
        [
          "name"=> "Trinidad y Tobago",
          "phone_code"=> "+1868",
          "capital"=> "Port of Spain",
          "flag"=> config('app.url')."/img/flag/tto.svg",
        ],
        [
          "name"=> "Túnez (África del Norte)",
          "phone_code"=> "+216",
          "capital"=> "Tunis",
          "flag"=> config('app.url')."/img/flag/tun.svg",
        ],
        [
          "name"=> "Turquía",
          "phone_code"=> "+90",
          "capital"=> "Ankara",
          "flag"=> config('app.url')."/img/flag/tur.svg",
        ],
        [
          "name"=> "Turkmenistán",
          "phone_code"=> "+993",
          "capital"=> "Ashgabat",
          "flag"=> config('app.url')."/img/flag/tkm.svg",
        ],
        [
          "name"=> "Islas Turcas y Caicos",
          "phone_code"=> "+1649",
          "capital"=> "Cockburn Town",
          "flag"=> config('app.url')."/img/flag/tca.svg",
        ],
        [
          "name"=> "Tuvalu",
          "phone_code"=>  "688",
          "capital"=> "Funafuti",
          "flag"=> config('app.url')."/img/flag/tuv.svg",
        ],
        [
          "name"=> "Uganda",
          "phone_code"=> "+256",
          "capital"=> "Kampala",
          "flag"=> config('app.url')."/img/flag/uga.svg",
          ],
        [
          "name"=> "Ucrania",
          "phone_code"=> "+380",
          "capital"=> "Kiev",
          "flag"=> config('app.url')."/img/flag/ukr.svg",
        ],
        [
          "name"=> "Emiratos Árabes Unidos",
          "phone_code"=> "+971",
          "capital"=> "Abu Dhabi",
          "flag"=> config('app.url')."/img/flag/are.svg",
        ],
        [
          "name"=> "Reino Unido de Gran Bretaña e Irlanda del Norte",
          "phone_code"=> "+44",
          "capital"=> "London",
          "flag"=> config('app.url')."/img/flag/gbr.svg",
        ],
        [
          "name"=> "Estados Unidos de América",
          "phone_code"=> "+1",
          "capital"=> "Washington, D.C.",
          "flag"=> config('app.url')."/img/flag/usa.svg",
        ],
        [
          "name"=> "Uruguay",
          "phone_code"=> "+598",
          "capital"=> "Montevideo",
          "flag"=> config('app.url')."/img/flag/ury.svg",
        ],
        [
          "name"=> "Uzbekistan",
          "phone_code"=> "+998",
          "capital"=> "Tashkent",
          "flag"=> config('app.url')."/img/flag/uzb.svg",
        ],
        [
          "name"=> "Vanuatu",
          "phone_code"=> "+678",
          "capital"=> "Port Vila",
          "flag"=> config('app.url')."/img/flag/vut.svg",
        ],
        [
          "name"=> "República Bolivariana de Venezuela",
          "phone_code"=> "+58",
          "capital"=> "Caracas",
          "flag"=> config('app.url')."/img/flag/ven.svg",
        ],
        [
          "name"=> "Vietnam",
          "phone_code"=> "+84",
          "capital"=> "Hanoi",
          "flag"=> config('app.url')."/img/flag/vnm.svg",
        ],
        [
          "name"=> "Wallis y Futuna",
          "phone_code"=> "+681",
          "capital"=> "Mata-Utu",
          "flag"=> config('app.url')."/img/flag/wlf.svg",
        ],
        [
          "name"=> "Sahara Occidental",
          "phone_code"=> "+212",
          "capital"=> "El Aaiún",
          "flag"=> config('app.url')."/img/flag/esh.svg",
        ],
        [
          "name"=> "Yemen",
          "phone_code"=> "+967",
          "capital"=> "Sana'a",
          "flag"=> config('app.url')."/img/flag/yem.svg",
        ],
        [
          "name"=> "Zambia",
          "phone_code"=> "+260",
          "capital"=> "Lusaka",
          "flag"=> config('app.url')."/img/flag/zmb.svg",
        ],
        [
          "name"=> "Zimbabue",
          "phone_code"=> "+263",
          "capital"=> "Harare",
          "flag"=> config('app.url')."/img/flag/zwe.svg",
        ]
        ];
    }
}
